name: main
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas=0.22.0
  - python==3.6
  - scikit-learn==0.19.1
  - xgboost==0.71
  - pip:
    - pyarrow
    - mlflow
    - tensorflow==1.8.0
